### ISSUE TITLE
Maybe you should copy a syncmap.go as a template, not user's GOROOT

### ISSUE THREAD

**Issue by MaruHyl** [a8m/syncmap#1]
Different versions of syncmap.go are different, including unexport methods, fields, variables and so on. Users may fail in some old go-version.
So you can use a template to keep the program stable and update with the go version.

**Comment by a8m** [comment]
There are [daily CI tests](https://travis-ci.com/a8m/syncmap) that make sure the code-generation is stable, and aligned with the latest changes.
`syncmap` will continue to support Go 1.11 and higher (including tip/master).

Anyway, thanks for you suggestion.
