### ISSUE TITLE
syncmap: function was deleted

### ISSUE THREAD

**Issue by sneko** [a8m/syncmap#7]
Hi @a8m ,

No matter which example command you mentioned in the doc' I'm always ending with this error:
```
sneko@sneko XXXXX % go run github.com/a8m/syncmap -name IntMap "map[int]int"
syncmap: function was deleted
```

I also tried directly `yncmap -name IntMap "map[int]int"` but same error.

Any idea of what I'm missing that triggers (?)
https://github.com/a8m/syncmap/blob/4bbbd178de97432c071e2d70312b77ec0039fefe/syncmap.go#L128

Thank you,

**Comment by a8m** [comment]
Hey @sneko, what Go version and syncmap version do you use?

Can you please install syncmap with the following command and report if this still happens?

```
go get -u github.com/a8m/syncmap@master
```

Thanks 🙏

**Comment by sneko** [comment]
@a8m according to my `go.mod` it was using:
```
v0.0.0-20200818084611-4bbbd178de97
```
(commit: https://github.com/a8m/syncmap/commit/4bbbd178de97432c071e2d70312b77ec0039fefe)

I'm on `go version go1.14.3 darwin/amd64`.

After upgrading with `go get -u github.com/a8m/syncmap@master` I'm still seeing the `syncmap: function was deleted` error.

**Comment by a8m** [comment]
The project supports the 2 latest Go versions (1.15, 1.16) atm.
If you want to use it in Go 1.14, you should install some previous version that works with Go 1.14. For example, https://github.com/a8m/syncmap/commit/9720640411271335d6e73d2155f75592487ea92a

**Comment by sneko** [comment]
Indeed, just try the basic example command and it generates the file 👍 

@a8m what do you recommend me to do: to stay with Go v1.14 and everything should be fine? Or upgrade my Go v1.15+ if possible because for file generation there are important changes.

(just want to clarify if that's fine inside a time to use different Go versions (v1.14, v1.15) and if the file will look the same when regenerating or should we align all...)

**Comment by a8m** [comment]
> @a8m what do you recommend me to do: to stay with Go v1.14 and everything should be fine? Or upgrade to Go v1.15+ if possible because for file generation there are important changes.

I'll suggest you to upgrade at least to Go 1.15, because AFAIK most of the OSS projects support the 2 latest versions. 

> (just want to clarify if that's fine inside my team to use different Go versions (v1.14, v1.15) so the file will look the same when regenerating or should we align all...)

The generated file is based on the Go version ([read here](https://github.com/a8m/syncmap#how-does-it-work)). If you use Go modules and use `go run` instead of global installation, that's fine. Different projects can use different versions.
